# Generated by Django 5.1 on 2024-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='interesse',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='interesses/'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/'),
        ),
    ]
