# Generated by Django 5.1 on 2024-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_curso_imagem_interesse_imagem_sobre_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='interesse',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='nome',
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
