# Generated by Django 5.1 on 2024-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_curso_descricao_remove_curso_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='interesse',
            options={'verbose_name': 'Interesse', 'verbose_name_plural': 'Interesses'},
        ),
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Sobre', 'verbose_name_plural': 'Sobre Mim'},
        ),
        migrations.AddField(
            model_name='sobre',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/sobre_mim/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_conclusao',
            field=models.DateField(verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título do Interesse'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='biografia',
            field=models.TextField(verbose_name='Biografia'),
        ),
    ]
